# Generated by Django 4.1.2 on 2022-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Contact_no', models.IntegerField(unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
