# Generated by Django 4.1.2 on 2022-11-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Contact_no', models.IntegerField(unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Books', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
            ],
        ),
    ]
