# Generated by Django 4.1.2 on 2022-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0002_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('Book_name', models.CharField(max_length=20)),
                ('Author_name', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=200)),
            ],
        ),
    ]
